language: node_js
node_js:
- '0.10'
- '0.12'
before_script:
- npm install -g .
- npm install -g jake
- npm install -g titanium
- mkdir ~/.titanium
- cp ./cli_config.json ~/.titanium/config.json
deploy:
  provider: npm
  email: npmjs@appcelerator.com
  api_key:
    secure: YDvhcMdwm6NX7vAQ7NwqC2m5YakaQhrPios6KfJNbYdd5aAZRyNkmYWRtgZN94zV2v/EmfodqESDdxHi89IoyHcdMX/bf80ECp8gyz/hs5SUeVpCJCeA0YZH5A+b9OabP0daS0iQ5p5/Ns/0ySoU0+J3zsvn5X27rADknsieM5A=
  on:
    tags: true
    repo: appcelerator/alloy
